# Generated by Django 3.0.5 on 2021-02-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('True_False', 'True_False'), ('one_word', 'one_word')], default=1, max_length=10),
        ),
    ]
