# Generated by Django 3.0.5 on 2021-02-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20210219_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Theory_answer',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
