# Generated by Django 3.0.5 on 2021-02-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_question_theory_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Theory_answer',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
