# Generated by Django 3.0.5 on 2021-02-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20210220_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Theory_answer',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('True_False', 'True_False')], default=1, max_length=10),
        ),
    ]
