# Generated by Django 3.0.5 on 2021-02-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210220_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('True_False', 'True_False'), ('Theory', 'Theory')], default=1, max_length=10),
        ),
    ]
