# Generated by Django 3.0.5 on 2021-02-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210221_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(upload_to='media'),
        ),
    ]
