# Generated by Django 3.0.5 on 2021-02-21 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20210221_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/Student/'),
        ),
    ]
