# Generated by Django 3.0.5 on 2021-02-22 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0019_test_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
