# Generated by Django 3.0.5 on 2021-02-22 08:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0020_auto_20210222_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='Academic_year',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notice',
            name='course_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student.Courses'),
        ),
    ]
