# Generated by Django 3.0.5 on 2021-02-22 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0021_auto_20210222_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='course_id',
        ),
    ]
