# Generated by Django 3.1.6 on 2021-02-24 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0022_remove_notice_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
