# Generated by Django 3.1.6 on 2021-02-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_auto_20210225_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='staff_id',
            field=models.CharField(default=1, max_length=16),
        ),
        migrations.AddField(
            model_name='students',
            name='pnr',
            field=models.CharField(default=1, max_length=16),
        ),
    ]
